# Name: Custom assertion functions/Throwing exceptions
SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodDeclaration" .
  ?n :name ?an1 .
  ?n (:in/:next)+ ?a .
  ?a :nodetype "ThrowStmt" .
  FILTER (CONTAINS(?an1, "assert")) .
}