# Name: Custom assertion functions/Containing assertions
SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodDeclaration" ;
     :name ?an1 ;
     (:in|:next)* ?a .
  ?a :nodetype "MethodCallExpr" ;
     :name ?an2 .
  FILTER (CONTAINS(?an1, "assert")) .
  FILTER (CONTAINS(?an2, "assert")) .
}
