# Name: Assertion of literals
SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodCallExpr" ;
     :name ?an ;
     :params ?a .
  VALUES (?an) {("assertEquals") ("assertNotEquals")} .
  ?a :arg1/:nodetype ?t1 ;
     :arg2/:nodetype ?t2 .
  FILTER (CONTAINS(?t1, "Literal")) .
  FILTER (CONTAINS(?t2, "Literal")) .
  FILTER NOT EXISTS {
    ?a :arg3 ?x .
  } .
}