# Name: Compound assertions/Nested
SELECT DISTINCT ?n WHERE {
  ?n :name ?a ;
     :params/:arg1 ?x ;
     :params/:arg2 ?y .
  FILTER (CONTAINS(?a, "assert")) .
  ?x :nodetype "BinaryExpr" ;
     :operator ?ox ;
     :in+ ?y .
  ?y :nodetype "BinaryExpr" ;
     :operator ?oy .
  VALUES (?ox) {("&&") ("||")} .
  VALUES (?oy) {("&&") ("||")} .
}
