# Name: Equality between/Maps
SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodCallExpr" ;
     :name ?an .
  ?n :params/:arg1/:resolvedtype/:instanceof "java.util.Map" .
  FILTER (CONTAINS(?an, "assert"))
}
