# Name: Compound assertions/Total
SELECT DISTINCT ?n WHERE {
  ?n :name ?a ;
     :params/:arg1 ?x .
  FILTER (CONTAINS(?a, "assert")) .
  ?x :nodetype "BinaryExpr" ;
     :operator ?o .
  VALUES (?o) {("&&") ("||")}
}
