# Name: Equality between/Different types
SELECT ?n WHERE {
  ?n :nodetype "MethodCallExp" ;
     :name ?an ;
     :params/:arg1/:type ?t1 ;
     :params/:arg2/:type ?t2 .
  VALUES (?an) {("assertEquals") ("assertNotEquals")} .
  FILTER (?t1 != ?t2) .
}
