# Name: Iterated assertions
SELECT DISTINCT ?n WHERE {
  ?n :nodetype ?t ;
     :in/(:in|:next)*/:name ?a .
  VALUES (?t) {("ForStmt") ("WhileStmt") ("DoStmt")} .
  FILTER (CONTAINS(?a, "assert")) .
}