# Name: Negated assertion
SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodCallExpr" ;
     :name ?a ;
     :params/:arg1 ?b .
  FILTER (CONTAINS(?a, "assert")) .
  ?b :nodetype "UnaryExpr" ;
     :operator "!" .
}