# Name: Overly generic assertions

SELECT DISTINCT ?n WHERE {
  ?n :annotations/:name "Test" ;
     :in/(:in|:next)* ?a .
  ?a :nodetype "MethodCallExpr" ;
     :name ?an ;
     :params/:arg1 ?arg .
  VALUES (?an) {("assertTrue") ("assertFalse")} .
  
  {
    SELECT ?arg WHERE {
      ?arg :nodetype "MethodCallExpr" ;
           :name "equals" .
    }
  }
  UNION
  {
    SELECT ?arg WHERE {
      ?arg :nodetype "BinaryExpr" ;
           :operator ?o .
      VALUES (?o) {("==") ("!=") ("<") (">") ("<=") (">=") } .
    }
  }
}
