# Name: Recursive assertions

SELECT DISTINCT ?n WHERE {
  ?n :annotations/:name "Test" ;
     :in ?c .

  ?c :nodetype "MethodCallExpr" ;
        :name ?name ;
        :declaration ?decl .
  
  FILTER(STRSTARTS(?name, "assert")) .
  
  ?decl :in/(:in|:next)* ?other .
  ?other :nodetype "MethodCallExpr" ;
         :name ?othername .
  
  FILTER (?name = ?othername) .
}
