# Name: Recursive assertions

SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodDeclaration" ;
        :name ?name .
  
  FILTER(STRSTARTS(?name, "assert")) .
  
  ?n :in/(:in|:next)* ?other .
  ?other :nodetype "MethodCallExpr" ;
         :name ?othername .
  
  FILTER (?name = ?othername) .
}
