# Name: Reference equality

SELECT DISTINCT ?n WHERE {
  ?n :nodetype "MethodDeclaration" ;
     :annotations/:name "Test" ;
     :in/(:in|:next)* ?call .
  ?call :nodetype "MethodCallExpr" ;
        :name ?callname .
  VALUES (?callname) {("assertTrue") ("assertFalse")} .
  
  ?call :params/:arg1 ?arg .
  ?arg  :nodetype "BinaryExpr" .
  
  ?arg  :arg1/:resolvedtype ?t1 ;
        :arg2/:resolvedtype ?t2 .
  FILTER (?t1 NOT IN ("int", "boolean", "float", "double", "java.lang.Integer", "java.lang.Boolean", "java.lang.Float", "java.lang.Double")) .
  FILTER (?t2 NOT IN ("int", "boolean", "float", "double", "java.lang.Integer", "java.lang.Boolean", "java.lang.Float", "java.lang.Double")) .
}