# Name: Dependencies between test classes
SELECT DISTINCT ?n WHERE {
  ?n     :nodetype "ClassOrInterfaceDeclaration" ;
         :name ?name1 ;
         (:in|:next)* ?md .
  ?md    :nodetype "MethodDeclaration" ;
         :annotations/:name "Test" ;
         (:in|:next)* ?mc .
  ?mc    :nodetype "MethodCallExpr" ;
         :scope ?s .
  ?s     :resolvedtype ?name2 .
  FILTER (CONTAINS(?name2, "Test")) .
  FILTER (?name1 != ?name2) .
}